import "./globals.css";
import { Toaster } from "sonner";
export const metadata = {
  title: "BuySense",
  description: "Generated by create next app",
  icons: {
    icon: "/logo2.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
